<?php

use PHPUnit\Framework\TestCase;

require_once ('Class\DBConnection.php');
require_once ('Class\Event.php');
require_once ('Class\User.php');
require_once ('Class\ToGo.php');
require_once ('Class\Filter.php');
require_once ('Class\ImgUpload.php');


class Test extends TestCase
{
      public function setUp(): void
      {
          parent::setUp(); // TODO: Change the autogenerated stub
      }
      public function tearDown(): void
      {
          parent::tearDown(); // TODO: Change the autogenerated stub
      }

      public function testServerConnection()
      { //sprawdzamy czy nasze połączenie nie jest false (jeśli test jest ok to znaczy, że łaczymy się z bazą)
          $connObj = new DBConnection();
          $connObj->returnConnection();
          $this->assertTrue($connObj->returnConnection() !== false);
      }

    public function testFirstTest()
    {       $user = new User();
        $user->setID(1);
        $this->assertEquals(1,$user->getId());
    }

    public function testSecondTest()
    {
      $user = new User();
      $user->logout('login');
      $this->assertEquals('',$user->doLogin());
    }

    public function testThirdTest() //klasa User posiada atrybut _haslo
    {
        $this -> assertClassHasAttribute ( '_haslo' ,User:: class );
    }

    public function testEmail()
    {
        $user = new User();
        $this->assertEquals('', $user->setEmail('j.kowalski@gmail.com'));
    }

    public function testFourTest(){
          $user = new User();
          $user->getSession(true);
          $this->assertTrue($user->getSession() !== true);
    }
}
